setopt ALWAYS_TO_END
setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_PUSHD
setopt AUTO_RESUME
setopt CDABLE_VARS
setopt CORRECT
setopt EXTENDED_GLOB
setopt GLOB_DOTS
setopt LONG_LIST_JOBS
setopt NOTIFY
setopt PUSHD_MINUS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME
setopt PRINT_EIGHT_BIT
setopt REC_EXACT

unsetopt AUTO_PARAM_SLASH
unsetopt BEEP
unsetopt BG_NICE
unsetopt CLOBBER
