#!/bin/sh

bspc desktop ^1 --rename 一
bspc monitor --add-desktops 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#000000'
bspc config focused_border_color '#000000'

bspc config growth_factor        10

# bspc rule --add <pattern>

$XDG_CONFIG_HOME/bspwm/panel &
