#!/bin/sh

bspc monitor --reset-desktops 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config growth_factor        1.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#000000'
bspc config focused_border_color '#000000'

bspc rule --add keepassx --floating

$XDG_CONFIG_HOME/bspwm/panel &
