#!/bin/sh

bspc config border_width         4
bspc config window_gap           4
bspc config split_ratio          0.5
bspc config growth_factor        1.0
bspc config auto_cancel          true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color           '#002b36'
bspc config focused_border_color          '#268bd2'
bspc config presel_border_color           '#858900'
bspc config normal_sticky_border_color    '#b58900'
bspc config focused_sticky_border_color   '#268bd2'
bspc config urgent_border_color           '#dc322f'

bspc monitor --reset-desktops         

bspc rule --add crx_hbdpomandigafcibbmofojjchbcdagbl desktop=^8
bspc rule --add crx_pjkljhegncpnkpknbcohdijeoejaedia desktop=^9
bspc rule --add keepassx floating=on
bspc rule --add sxiv fullscreen=on

$XDG_CONFIG_HOME/bspwm/panel &
