#!/bin/sh

if [ $(pgrep -cx $XDG_CONFIG_HOME/bspwm/panel) -gt 1 ]; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding 18

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

xtitle -sf 'T%s' > $PANEL_FIFO &
bspc control --subscribe > $PANEL_FIFO &
$XDG_CONFIG_HOME/bspwm/system > $PANEL_FIFO &

cat $PANEL_FIFO | $XDG_CONFIG_HOME/bspwm/status | bar \
  -g x18 -u 0 -B "#ff002b36" -F "#fffdf6e3" \
  -f "-*-stlarch-medium-*-*-*-10-*-*-*-*-*-*-*,-artwiz-anorexia-medium-*-*-*-11-*-*-*-*-*-*-*"
