#!/bin/sh

if [ $(pgrep -cx $XDG_CONFIG_HOME/bspwm/panel) -gt 1 ]; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

bspc config top_padding 18

xtitle -sf 'T%s' > $PANEL_FIFO &
conky --config="$XDG_CONFIG_HOME/bspwm/conky" > $PANEL_FIFO &
cat $PANEL_FIFO | $XDG_CONFIG_HOME/bspwm/status | bar
