#!/bin/sh

chromium &
subl &
/usr/bin/chromium --app-id=hbdpomandigafcibbmofojjchbcdagbl --profile-directory=Default
/usr/bin/chromium --app-id=pjkljhegncpnkpknbcohdijeoejaedia --profile-directory=Default
