#!/bin/sh

while read -r line; do
  case $line in
    S*)
      # system output
      system="${line#?}"
      ;;
    T*)
      # xtitle output
      title="%{F#ffb9ca4a}${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm=" "
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [OFU]*)
            # focused occupied/free/urgent desktops
            wm="$wm %{F#ffb9ca4a}${name} "
            ;;
          o*)
            # occupied desktop
            wm="$wm %{F#ffc397d8}${name} "
            ;;
          f*)
            # free desktop
            wm="$wm %{F#ff373b41}${name} "
            ;;
          u*)
            # urgent desktop
            wm="$wm %{F#ffd54e53}${name} "
            ;;
        esac
        shift
      done
      ;;
  esac

  printf "%s\n" "$wm   $title %{r}$system"
done
