#!/bin/sh

while read -r line ; do
  case $line in
    C*)
      # conky output
      conky="${line#?}"
      ;;
    T*)
      # xtitle output
      title="\\f5${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            # focused occupied desktop
            wm_infos="$wm_infos \\f2${name}"
            ;;
          F*)
            # focused free desktop
            wm_infos="$wm_infos \\f2${name}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="$wm_infos \\f2${name}"
            ;;
          o*)
            # occupied desktop
            wm_infos="$wm_infos \\fr${name}"
            ;;
          f*)
            # free desktop
            wm_infos="$wm_infos \\f7${name}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos \\f1${name}"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "\\l $wm_infos   $title \\r $conky  "
done
